### ISSUE TITLE
As a Student, I want to select specific topics within a course for quizzes, so that I can focus on areas where I need improvement.

### ISSUE THREAD

**Issue by akshayvijaynair** [akshayvijaynair/ghor-kalyug#2]
> [!IMPORTANT]
>  AC 1	Students can select a range of topics for a quiz.
>  AC 2	Students can see quizes generated by an LLM

## Tasks
- [x] Integrate Gemini API
- [x] Send user request for quiz on specific topic
- [ ] Provide basic topic list
- [ ] Show quiz in MCQ format
