### ISSUE TITLE
As a Teacher, I want to create and upload a question bank, so that my students have access to relevant practice material.

### ISSUE THREAD

**Issue by akshayvijaynair** [akshayvijaynair/ghor-kalyug#9]
> [!IMPORTANT]
> AC 1	Teachers can add questions and knowledge in bulk via supported file formats.
> AC 2	The system supports various question types (multiple-choice, true/false, short answer).
> AC 3     Teachers can add questions individually (OPTIONAL Acceptance Criteria)

## Tasks
- [ ] Add in support for uploading documents
- [ ] Add in support for categorizing documents based on knowledge or question bank
- [ ] Add in support for who can view documents
- [ ] Add in support for who can quiz from documents
